pref("extensions.zotlink.attachmentMoveRoot", "D:\\OneDrive\\Zotero");
pref("extensions.zotlink.attachmentMoveShortcut", "");
pref("extensions.zotlink.autoRenameAttachmentsEnabled", false);
pref("extensions.zotlink.attachmentRenamePattern", "{author} {year} {title}");
pref("extensions.zotlink.autoWritePDFDOIMetadata", true);
pref("extensions.zotlink.autoAlignPDFPageLabels", true);
pref("extensions.zotlink.autoExtractArticleHistory", false);
pref("extensions.zotlink.autoSetPDFOpenToFirstPage", true);
pref("extensions.zotlink.autoSetPDFDisplayTitleFileName", true);
pref("extensions.zotlink.lastMoveReport", "");
pref("extensions.zotlink.lastIndexReport", "");
pref("extensions.zotlink.attachmentFileIndex", "{}");
